package com.zyt.heima.entity;

import java.util.Date;

public class Blog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.blogId
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    private String blogid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.createTime
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.blogtag
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    private String blogtag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.blogTitle
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    private String blogtitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.readnum
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    private Integer readnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.goodnum
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    private Integer goodnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.userId
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.blogText
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    private String blogtext;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.blogId
     *
     * @return the value of blog.blogId
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    public String getBlogid() {
        return blogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.blogId
     *
     * @param blogid the value for blog.blogId
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    public void setBlogid(String blogid) {
        this.blogid = blogid == null ? null : blogid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.createTime
     *
     * @return the value of blog.createTime
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.createTime
     *
     * @param createtime the value for blog.createTime
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.blogtag
     *
     * @return the value of blog.blogtag
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    public String getBlogtag() {
        return blogtag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.blogtag
     *
     * @param blogtag the value for blog.blogtag
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    public void setBlogtag(String blogtag) {
        this.blogtag = blogtag == null ? null : blogtag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.blogTitle
     *
     * @return the value of blog.blogTitle
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    public String getBlogtitle() {
        return blogtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.blogTitle
     *
     * @param blogtitle the value for blog.blogTitle
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    public void setBlogtitle(String blogtitle) {
        this.blogtitle = blogtitle == null ? null : blogtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.readnum
     *
     * @return the value of blog.readnum
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    public Integer getReadnum() {
        return readnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.readnum
     *
     * @param readnum the value for blog.readnum
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    public void setReadnum(Integer readnum) {
        this.readnum = readnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.goodnum
     *
     * @return the value of blog.goodnum
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    public Integer getGoodnum() {
        return goodnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.goodnum
     *
     * @param goodnum the value for blog.goodnum
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    public void setGoodnum(Integer goodnum) {
        this.goodnum = goodnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.userId
     *
     * @return the value of blog.userId
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.userId
     *
     * @param userid the value for blog.userId
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.blogText
     *
     * @return the value of blog.blogText
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    public String getBlogtext() {
        return blogtext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.blogText
     *
     * @param blogtext the value for blog.blogText
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    public void setBlogtext(String blogtext) {
        this.blogtext = blogtext == null ? null : blogtext.trim();
    }
}