package com.zyt.heima.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CommentsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comments
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comments
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comments
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    public CommentsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table comments
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCommidIsNull() {
            addCriterion("commID is null");
            return (Criteria) this;
        }

        public Criteria andCommidIsNotNull() {
            addCriterion("commID is not null");
            return (Criteria) this;
        }

        public Criteria andCommidEqualTo(String value) {
            addCriterion("commID =", value, "commid");
            return (Criteria) this;
        }

        public Criteria andCommidNotEqualTo(String value) {
            addCriterion("commID <>", value, "commid");
            return (Criteria) this;
        }

        public Criteria andCommidGreaterThan(String value) {
            addCriterion("commID >", value, "commid");
            return (Criteria) this;
        }

        public Criteria andCommidGreaterThanOrEqualTo(String value) {
            addCriterion("commID >=", value, "commid");
            return (Criteria) this;
        }

        public Criteria andCommidLessThan(String value) {
            addCriterion("commID <", value, "commid");
            return (Criteria) this;
        }

        public Criteria andCommidLessThanOrEqualTo(String value) {
            addCriterion("commID <=", value, "commid");
            return (Criteria) this;
        }

        public Criteria andCommidLike(String value) {
            addCriterion("commID like", value, "commid");
            return (Criteria) this;
        }

        public Criteria andCommidNotLike(String value) {
            addCriterion("commID not like", value, "commid");
            return (Criteria) this;
        }

        public Criteria andCommidIn(List<String> values) {
            addCriterion("commID in", values, "commid");
            return (Criteria) this;
        }

        public Criteria andCommidNotIn(List<String> values) {
            addCriterion("commID not in", values, "commid");
            return (Criteria) this;
        }

        public Criteria andCommidBetween(String value1, String value2) {
            addCriterion("commID between", value1, value2, "commid");
            return (Criteria) this;
        }

        public Criteria andCommidNotBetween(String value1, String value2) {
            addCriterion("commID not between", value1, value2, "commid");
            return (Criteria) this;
        }

        public Criteria andCommcontextIsNull() {
            addCriterion("commContext is null");
            return (Criteria) this;
        }

        public Criteria andCommcontextIsNotNull() {
            addCriterion("commContext is not null");
            return (Criteria) this;
        }

        public Criteria andCommcontextEqualTo(String value) {
            addCriterion("commContext =", value, "commcontext");
            return (Criteria) this;
        }

        public Criteria andCommcontextNotEqualTo(String value) {
            addCriterion("commContext <>", value, "commcontext");
            return (Criteria) this;
        }

        public Criteria andCommcontextGreaterThan(String value) {
            addCriterion("commContext >", value, "commcontext");
            return (Criteria) this;
        }

        public Criteria andCommcontextGreaterThanOrEqualTo(String value) {
            addCriterion("commContext >=", value, "commcontext");
            return (Criteria) this;
        }

        public Criteria andCommcontextLessThan(String value) {
            addCriterion("commContext <", value, "commcontext");
            return (Criteria) this;
        }

        public Criteria andCommcontextLessThanOrEqualTo(String value) {
            addCriterion("commContext <=", value, "commcontext");
            return (Criteria) this;
        }

        public Criteria andCommcontextLike(String value) {
            addCriterion("commContext like", value, "commcontext");
            return (Criteria) this;
        }

        public Criteria andCommcontextNotLike(String value) {
            addCriterion("commContext not like", value, "commcontext");
            return (Criteria) this;
        }

        public Criteria andCommcontextIn(List<String> values) {
            addCriterion("commContext in", values, "commcontext");
            return (Criteria) this;
        }

        public Criteria andCommcontextNotIn(List<String> values) {
            addCriterion("commContext not in", values, "commcontext");
            return (Criteria) this;
        }

        public Criteria andCommcontextBetween(String value1, String value2) {
            addCriterion("commContext between", value1, value2, "commcontext");
            return (Criteria) this;
        }

        public Criteria andCommcontextNotBetween(String value1, String value2) {
            addCriterion("commContext not between", value1, value2, "commcontext");
            return (Criteria) this;
        }

        public Criteria andPartentidIsNull() {
            addCriterion("partentId is null");
            return (Criteria) this;
        }

        public Criteria andPartentidIsNotNull() {
            addCriterion("partentId is not null");
            return (Criteria) this;
        }

        public Criteria andPartentidEqualTo(String value) {
            addCriterion("partentId =", value, "partentid");
            return (Criteria) this;
        }

        public Criteria andPartentidNotEqualTo(String value) {
            addCriterion("partentId <>", value, "partentid");
            return (Criteria) this;
        }

        public Criteria andPartentidGreaterThan(String value) {
            addCriterion("partentId >", value, "partentid");
            return (Criteria) this;
        }

        public Criteria andPartentidGreaterThanOrEqualTo(String value) {
            addCriterion("partentId >=", value, "partentid");
            return (Criteria) this;
        }

        public Criteria andPartentidLessThan(String value) {
            addCriterion("partentId <", value, "partentid");
            return (Criteria) this;
        }

        public Criteria andPartentidLessThanOrEqualTo(String value) {
            addCriterion("partentId <=", value, "partentid");
            return (Criteria) this;
        }

        public Criteria andPartentidLike(String value) {
            addCriterion("partentId like", value, "partentid");
            return (Criteria) this;
        }

        public Criteria andPartentidNotLike(String value) {
            addCriterion("partentId not like", value, "partentid");
            return (Criteria) this;
        }

        public Criteria andPartentidIn(List<String> values) {
            addCriterion("partentId in", values, "partentid");
            return (Criteria) this;
        }

        public Criteria andPartentidNotIn(List<String> values) {
            addCriterion("partentId not in", values, "partentid");
            return (Criteria) this;
        }

        public Criteria andPartentidBetween(String value1, String value2) {
            addCriterion("partentId between", value1, value2, "partentid");
            return (Criteria) this;
        }

        public Criteria andPartentidNotBetween(String value1, String value2) {
            addCriterion("partentId not between", value1, value2, "partentid");
            return (Criteria) this;
        }

        public Criteria andCommtimeIsNull() {
            addCriterion("commTime is null");
            return (Criteria) this;
        }

        public Criteria andCommtimeIsNotNull() {
            addCriterion("commTime is not null");
            return (Criteria) this;
        }

        public Criteria andCommtimeEqualTo(Date value) {
            addCriterion("commTime =", value, "commtime");
            return (Criteria) this;
        }

        public Criteria andCommtimeNotEqualTo(Date value) {
            addCriterion("commTime <>", value, "commtime");
            return (Criteria) this;
        }

        public Criteria andCommtimeGreaterThan(Date value) {
            addCriterion("commTime >", value, "commtime");
            return (Criteria) this;
        }

        public Criteria andCommtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("commTime >=", value, "commtime");
            return (Criteria) this;
        }

        public Criteria andCommtimeLessThan(Date value) {
            addCriterion("commTime <", value, "commtime");
            return (Criteria) this;
        }

        public Criteria andCommtimeLessThanOrEqualTo(Date value) {
            addCriterion("commTime <=", value, "commtime");
            return (Criteria) this;
        }

        public Criteria andCommtimeIn(List<Date> values) {
            addCriterion("commTime in", values, "commtime");
            return (Criteria) this;
        }

        public Criteria andCommtimeNotIn(List<Date> values) {
            addCriterion("commTime not in", values, "commtime");
            return (Criteria) this;
        }

        public Criteria andCommtimeBetween(Date value1, Date value2) {
            addCriterion("commTime between", value1, value2, "commtime");
            return (Criteria) this;
        }

        public Criteria andCommtimeNotBetween(Date value1, Date value2) {
            addCriterion("commTime not between", value1, value2, "commtime");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userId is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userId is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(String value) {
            addCriterion("userId =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(String value) {
            addCriterion("userId <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(String value) {
            addCriterion("userId >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(String value) {
            addCriterion("userId >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(String value) {
            addCriterion("userId <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(String value) {
            addCriterion("userId <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLike(String value) {
            addCriterion("userId like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotLike(String value) {
            addCriterion("userId not like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<String> values) {
            addCriterion("userId in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<String> values) {
            addCriterion("userId not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(String value1, String value2) {
            addCriterion("userId between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(String value1, String value2) {
            addCriterion("userId not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andBlogidIsNull() {
            addCriterion("blogId is null");
            return (Criteria) this;
        }

        public Criteria andBlogidIsNotNull() {
            addCriterion("blogId is not null");
            return (Criteria) this;
        }

        public Criteria andBlogidEqualTo(String value) {
            addCriterion("blogId =", value, "blogid");
            return (Criteria) this;
        }

        public Criteria andBlogidNotEqualTo(String value) {
            addCriterion("blogId <>", value, "blogid");
            return (Criteria) this;
        }

        public Criteria andBlogidGreaterThan(String value) {
            addCriterion("blogId >", value, "blogid");
            return (Criteria) this;
        }

        public Criteria andBlogidGreaterThanOrEqualTo(String value) {
            addCriterion("blogId >=", value, "blogid");
            return (Criteria) this;
        }

        public Criteria andBlogidLessThan(String value) {
            addCriterion("blogId <", value, "blogid");
            return (Criteria) this;
        }

        public Criteria andBlogidLessThanOrEqualTo(String value) {
            addCriterion("blogId <=", value, "blogid");
            return (Criteria) this;
        }

        public Criteria andBlogidLike(String value) {
            addCriterion("blogId like", value, "blogid");
            return (Criteria) this;
        }

        public Criteria andBlogidNotLike(String value) {
            addCriterion("blogId not like", value, "blogid");
            return (Criteria) this;
        }

        public Criteria andBlogidIn(List<String> values) {
            addCriterion("blogId in", values, "blogid");
            return (Criteria) this;
        }

        public Criteria andBlogidNotIn(List<String> values) {
            addCriterion("blogId not in", values, "blogid");
            return (Criteria) this;
        }

        public Criteria andBlogidBetween(String value1, String value2) {
            addCriterion("blogId between", value1, value2, "blogid");
            return (Criteria) this;
        }

        public Criteria andBlogidNotBetween(String value1, String value2) {
            addCriterion("blogId not between", value1, value2, "blogid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table comments
     *
     * @mbg.generated do_not_delete_during_merge Sat Sep 28 15:20:08 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table comments
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}