package com.zyt.heima.entity;

public class Menuitem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menuitem.menuId
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    private String menuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menuitem.menuName
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    private String menuname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menuitem.pId
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    private String pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menuitem.menuUrl
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    private String menuurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menuitem.menuSort
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    private String menusort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menuitem.userId
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    private String userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menuitem.menuId
     *
     * @return the value of menuitem.menuId
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    public String getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menuitem.menuId
     *
     * @param menuid the value for menuitem.menuId
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    public void setMenuid(String menuid) {
        this.menuid = menuid == null ? null : menuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menuitem.menuName
     *
     * @return the value of menuitem.menuName
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    public String getMenuname() {
        return menuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menuitem.menuName
     *
     * @param menuname the value for menuitem.menuName
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    public void setMenuname(String menuname) {
        this.menuname = menuname == null ? null : menuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menuitem.pId
     *
     * @return the value of menuitem.pId
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menuitem.pId
     *
     * @param pid the value for menuitem.pId
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menuitem.menuUrl
     *
     * @return the value of menuitem.menuUrl
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    public String getMenuurl() {
        return menuurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menuitem.menuUrl
     *
     * @param menuurl the value for menuitem.menuUrl
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    public void setMenuurl(String menuurl) {
        this.menuurl = menuurl == null ? null : menuurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menuitem.menuSort
     *
     * @return the value of menuitem.menuSort
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    public String getMenusort() {
        return menusort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menuitem.menuSort
     *
     * @param menusort the value for menuitem.menuSort
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    public void setMenusort(String menusort) {
        this.menusort = menusort == null ? null : menusort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menuitem.userId
     *
     * @return the value of menuitem.userId
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menuitem.userId
     *
     * @param userid the value for menuitem.userId
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }
}