package com.zyt.heima.service;

import com.zyt.heima.entity.Comments;
import com.zyt.heima.entity.CommentsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CommentsDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    long countByExample(CommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    int deleteByExample(CommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    int deleteByPrimaryKey(String commid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    int insert(Comments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    int insertSelective(Comments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    List<Comments> selectByExample(CommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    Comments selectByPrimaryKey(String commid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") Comments record, @Param("example") CommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    int updateByExample(@Param("record") Comments record, @Param("example") CommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    int updateByPrimaryKeySelective(Comments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    int updateByPrimaryKey(Comments record);
}