package com.zyt.heima.dao;

import com.zyt.heima.entity.Menuitem;
import com.zyt.heima.entity.MenuitemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MenuitemDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    long countByExample(MenuitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    int deleteByExample(MenuitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    int deleteByPrimaryKey(String menuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    int insert(Menuitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    int insertSelective(Menuitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    List<Menuitem> selectByExample(MenuitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    Menuitem selectByPrimaryKey(String menuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") Menuitem record, @Param("example") MenuitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    int updateByExample(@Param("record") Menuitem record, @Param("example") MenuitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    int updateByPrimaryKeySelective(Menuitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem
     *
     * @mbg.generated Sat Sep 28 15:20:08 CST 2019
     */
    int updateByPrimaryKey(Menuitem record);
}